FROM bitnami/spark:3.5

USER root

# Create a proper "spark" user with UID 1001 so it doesn’t show "I have no name!"
RUN echo "spark:x:1001:0:Spark User:/home/spark:/bin/bash" >> /etc/passwd && \
    mkdir -p /home/spark && chown -R 1001:0 /home/spark

COPY spark-entrypoint.sh /usr/local/bin/spark-entrypoint.sh
RUN chmod +x /usr/local/bin/spark-entrypoint.sh

USER 1001
